
services:
  qure:
    image: dolanor/qure:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QURE_DOMAIN: ${QURE_DOMAIN}
      QURE_HOST:   ${QURE_HOST}
      QURE_PORT:   ${QURE_PORT}
    expose:
      - 4444
    ports:
      - 4444:4444
