
services:
  qure:
    image: dolanor/qure:v0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QURE_DOMAIN: ${QURE_DOMAIN}
      QURE_HOST:   ${QURE_HOST}
      QURE_PORT:   ${QURE_PORT}
      QURE_DB_DIR: ${QURE_DB_DIR}
    expose:
      - ${QURE_PORT}
    ports:
      - 4444:${QURE_PORT}
    volumes:
      - "db:${QURE_DB_DIR}"
    restart: always

volumes:
  db:
