
services:
  qure:
    image: dolanor/qure:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOMAIN: l.txg.re
    expose:
      - 4444
    ports:
      - 4444:4444
