
services:
  qure:
    image: dolanor/qure:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QURE_DOMAIN: ${QURE_DOMAIN}
      QURE_HOST:   ${QURE_HOST}
      QURE_PORT:   ${QURE_PORT}
      QURE_DB_DIR: ${QURE_DB_DIR}
    expose:
      - 4444
    ports:
      - 4444:4444
    volumes:
      - "db:${QURE_DB_DIR}"
    labels:
      - "traefik.instance=dsuite"
      - "traefik.enable=true"
      - "traefik.docker.network=dsuite_front"
      - "traefik.http.routers.qure.entrypoints=websecure"
      - "traefik.http.routers.qure.tls.certresolver=myresolver"
      - "traefik.http.routers.qure.rule=Host(`l.txg.re`)"
      - "traefik.http.services.qure.loadbalancer.server.port=4444"
    restart: always
    networks:
      - front

networks:
  front:
    external: true
    name: dsuite_front

volumes:
  db:
